<div id="header" align="center">
  <img src="https://media.giphy.com/media/3ohzdSfnSZJ23KcIWA/giphy-downsized-large.gif" width="100"/>
</div>

### Hi. It's me GEAROL8

<div id="badges">
<img src="https://img.shields.io/badge/Twitter-blue?style=for-the-badge&logo=twitter&logoColor=whit" ealt="Twitter Badge"/>
</div>" 

<!--
**Gearol8/gearol8** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
